/**
 * Ordered, per-feature migration chain.
 *
 * Each entry maps 1:1 to a file in this directory and corresponds to one
 * version row in the `schema_version` table. The order here is the order
 * migrations are applied — do not reorder existing entries; append new ones
 * at the end.
 */
import { M001_V1_SCHEMA, M001_V1_SCHEMA_VERSION } from "./001-v1-schema.js";
import { M002_V1_SPACE_AGENT_ASSIGNMENTS, M002_V1_SPACE_AGENT_ASSIGNMENTS_VERSION } from "./002-v1-space-agent-assignments.js";
import { M003_V1_SPACE_SKILLS, M003_V1_SPACE_SKILLS_VERSION } from "./003-v1-space-skills.js";
import { M004_V1_SPACE_RESOURCES, M004_V1_SPACE_RESOURCES_VERSION } from "./004-v1-space-resources.js";
import { M005_V1_SPACE_WORKSPACES, M005_V1_SPACE_WORKSPACES_VERSION } from "./005-v1-space-workspaces.js";
import { M006_V1_PROFILE_MODEL_CONFIG, M006_V1_PROFILE_MODEL_CONFIG_VERSION } from "./006-v1-profile-model-config.js";
import { M007_V1_GATEWAY_POLICY, M007_V1_GATEWAY_POLICY_VERSION } from "./007-v1-gateway-policy.js";
import { M008_V1_ORCHESTRATOR_COMMANDS, M008_V1_ORCHESTRATOR_COMMANDS_VERSION } from "./008-v1-orchestrator-commands.js";
import { M009_V1_SPACE_CONTEXT_TRANSFER, M009_V1_SPACE_CONTEXT_TRANSFER_VERSION } from "./009-v1-space-context-transfer.js";
import { M010_V1_SPACE_SHARING_ACCESS, M010_V1_SPACE_SHARING_ACCESS_VERSION } from "./010-v1-space-sharing-access.js";
import { M011_V1_SYNC_RUNTIME, M011_V1_SYNC_RUNTIME_VERSION } from "./011-v1-sync-runtime.js";
import { M012_V1_DEVICE_IDENTITIES, M012_V1_DEVICE_IDENTITIES_VERSION } from "./012-v1-device-identities.js";
import { M013_V1_SPACE_PRESET_APPLICATIONS, M013_V1_SPACE_PRESET_APPLICATIONS_VERSION } from "./013-v1-space-preset-applications.js";
import { M014_V1_SPACE_TEMPLATE_OWNERS, M014_V1_SPACE_TEMPLATE_OWNERS_VERSION } from "./014-v1-space-template-owners.js";
import { M015_V1_GATEWAY_CAPABILITY_GRANTS, M015_V1_GATEWAY_CAPABILITY_GRANTS_VERSION } from "./015-v1-gateway-capability-grants.js";
import { M016_V1_VOICE_USAGE_EVENTS, M016_V1_VOICE_USAGE_EVENTS_VERSION } from "./016-v1-voice-usage-events.js";
import { M017_V1_CONNECTOR_ARCHITECTURE, M017_V1_CONNECTOR_ARCHITECTURE_VERSION } from "./017-v1-connector-architecture.js";
import { M018_V1_PROVIDER_SECRET_REFS, M018_V1_PROVIDER_SECRET_REFS_VERSION } from "./018-v1-provider-secret-refs.js";
import { M019_V1_SPACE_MCP_ENDPOINTS, M019_V1_SPACE_MCP_ENDPOINTS_VERSION } from "./019-v1-space-mcp-endpoints.js";
import { M020_V1_SPACE_EXTERNAL_AGENT_BINDINGS, M020_V1_SPACE_EXTERNAL_AGENT_BINDINGS_VERSION } from "./020-v1-space-external-agent-bindings.js";
import { M021_V1_KNOWLEDGE_BASE_ENTRIES, M021_V1_KNOWLEDGE_BASE_ENTRIES_VERSION } from "./021-v1-knowledge-base-entries.js";
import { M022_V2_GATEWAY_SKILL_CATALOG, M022_V2_GATEWAY_SKILL_CATALOG_VERSION } from "./022-v2-gateway-skill-catalog.js";
import { M023_V2_AGENT_PRESETS, M023_V2_AGENT_PRESETS_VERSION } from "./023-v2-agent-presets.js";
import { M024_V2_ASSIGNMENT_PROMPT_CONTEXT, M024_V2_ASSIGNMENT_PROMPT_CONTEXT_VERSION } from "./024-v2-assignment-prompt-context.js";
import { M025_V2_SCHEDULER_JOBS, M025_V2_SCHEDULER_JOBS_VERSION } from "./025-v2-scheduler-jobs.js";
import { M026_V2_SHARE_RELAY_METADATA, M026_V2_SHARE_RELAY_METADATA_VERSION } from "./026-v2-share-relay-metadata.js";
import { M027_V2_SPACE_WORKSPACE_PROJECT_META, M027_V2_SPACE_WORKSPACE_PROJECT_META_VERSION } from "./027-v2-space-workspace-project-meta.js";
import { M028_V3_SPACE_WORKSPACE_METADATA_COLUMNS, M028_V3_SPACE_WORKSPACE_METADATA_COLUMNS_VERSION } from "./028-v3-space-workspace-metadata-columns.js";
import { M029_V2_COLLABORATION_CHANGESETS, M029_V2_COLLABORATION_CHANGESETS_VERSION } from "./029-v2-collaboration-changesets.js";
import { M030_V1_PROVIDER_CONFIGS, M030_V1_PROVIDER_CONFIGS_VERSION } from "./030-v1-provider-configs.js";
import { M031_V2_CHAT_SURFACE_V2, M031_V2_CHAT_SURFACE_V2_VERSION } from "./031-v2-chat-surface-v2.js";
import { M032_V2_TURNS_REPLY_TO_TURN_ID, M032_V2_TURNS_REPLY_TO_TURN_ID_VERSION } from "./032-v2-turns-reply-to-turn-id.js";
import { M033_V2_PROVIDER_CONNECTION_STATES_NAMESPACE, M033_V2_PROVIDER_CONNECTION_STATES_NAMESPACE_VERSION } from "./033-v2-provider-connection-states-namespace.js";
import { M034_V2_TURNS_SPACE_ACTOR_INDEX, M034_V2_TURNS_SPACE_ACTOR_INDEX_VERSION } from "./034-v2-turns-space-actor-index.js";
import { M035_V2_RUNTIME_RESET_LEDGER, M035_V2_RUNTIME_RESET_LEDGER_VERSION } from "./035-v2-runtime-reset-ledger.js";
import { M036_V2_PROVIDER_CONFIG_NATIVE_CLI_TOOLS, M036_V2_PROVIDER_CONFIG_NATIVE_CLI_TOOLS_VERSION } from "./036-v2-provider-config-native-cli-tools.js";
import { M037_V2_PROVIDER_CONFIG_AUTH_MODE, M037_V2_PROVIDER_CONFIG_AUTH_MODE_VERSION } from "./037-v2-provider-config-auth-mode.js";
import { M038_V2_USAGE_RECORD_TOKEN_ACCURACY, M038_V2_USAGE_RECORD_TOKEN_ACCURACY_VERSION } from "./038-v2-usage-record-token-accuracy.js";
import { M039_V2_SPACE_LIFECYCLE_TIMESTAMPS, M039_V2_SPACE_LIFECYCLE_TIMESTAMPS_VERSION } from "./039-v2-space-lifecycle-timestamps.js";
import { M040_V2_GATEWAY_WORKSPACE_DEFAULTS, M040_V2_GATEWAY_WORKSPACE_DEFAULTS_VERSION } from "./040-v2-gateway-workspace-defaults.js";
import { M041_V2_GATEWAY_RUNTIME_DEFAULTS, M041_V2_GATEWAY_RUNTIME_DEFAULTS_VERSION } from "./041-v2-gateway-runtime-defaults.js";
import { M042_V2_GATEWAY_EXTERNAL_CONNECTIVITY, M042_V2_GATEWAY_EXTERNAL_CONNECTIVITY_VERSION } from "./042-v2-gateway-external-connectivity.js";
import { M043_V3_IDENTITY_PERSONAS, M043_V3_IDENTITY_PERSONAS_VERSION } from "./043-v3-identity-personas.js";
import { M044_V4_SPACE_WORKSPACE_MANAGED_FOLDER_NAME, M044_V4_SPACE_WORKSPACE_MANAGED_FOLDER_NAME_VERSION } from "./044-v4-space-workspace-managed-folder-name.js";
import { M045_V5_VOICE_USAGE_CHANNEL_AND_PROVIDER_REGISTRY, M045_V5_VOICE_USAGE_CHANNEL_AND_PROVIDER_REGISTRY_VERSION } from "./045-v5-voice-usage-channel-and-provider-registry.js";
import { M046_V6_GATEWAY_LINKED_SKILL_INDEX, M046_V6_GATEWAY_LINKED_SKILL_INDEX_VERSION } from "./046-v6-gateway-linked-skill-index.js";
import { M047_V7_CONCIERGE_ESCALATION_REQUESTS, M047_V7_CONCIERGE_ESCALATION_REQUESTS_VERSION } from "./047-v7-concierge-escalation-requests.js";
import { M048_V8_WORKBENCH, M048_V8_WORKBENCH_VERSION } from "./048-v8-workbench.js";
import { M049_V9_AGENT_USAGE_SESSION_RUNTIME_METADATA, M049_V9_AGENT_USAGE_SESSION_RUNTIME_METADATA_VERSION } from "./049-v9-agent-usage-session-runtime-metadata.js";
import { M050_V10_WORKBENCH_EXECUTION_CONTEXT, M050_V10_WORKBENCH_EXECUTION_CONTEXT_VERSION } from "./050-v10-workbench-execution-context.js";
import { M051_V11_GATEWAY_EXTERNAL_CONNECTIVITY_FUNNEL, M051_V11_GATEWAY_EXTERNAL_CONNECTIVITY_FUNNEL_VERSION } from "./051-v11-gateway-external-connectivity-funnel.js";
import { M052_V12_INVITE_TOKENS, M052_V12_INVITE_TOKENS_VERSION } from "./052-v12-invite-tokens.js";
import { M053_V13_APPLE_NOTIFICATIONS, M053_V13_APPLE_NOTIFICATIONS_VERSION } from "./053-v13-apple-notifications.js";
import { M054_V14_RUNTIME_LEDGER_TURN_ID, M054_V14_RUNTIME_LEDGER_TURN_ID_VERSION } from "./054-v14-runtime-ledger-turn-id.js";
import { SEED_STATEMENTS } from "./seed.js";

export interface Migration {
  readonly version: string;
  readonly up: readonly string[];
}

export const MIGRATION_CHAIN: readonly Migration[] = [
  { version: M001_V1_SCHEMA_VERSION, up: M001_V1_SCHEMA },
  { version: M002_V1_SPACE_AGENT_ASSIGNMENTS_VERSION, up: M002_V1_SPACE_AGENT_ASSIGNMENTS },
  { version: M003_V1_SPACE_SKILLS_VERSION, up: M003_V1_SPACE_SKILLS },
  { version: M004_V1_SPACE_RESOURCES_VERSION, up: M004_V1_SPACE_RESOURCES },
  { version: M005_V1_SPACE_WORKSPACES_VERSION, up: M005_V1_SPACE_WORKSPACES },
  { version: M006_V1_PROFILE_MODEL_CONFIG_VERSION, up: M006_V1_PROFILE_MODEL_CONFIG },
  { version: M007_V1_GATEWAY_POLICY_VERSION, up: M007_V1_GATEWAY_POLICY },
  { version: M008_V1_ORCHESTRATOR_COMMANDS_VERSION, up: M008_V1_ORCHESTRATOR_COMMANDS },
  { version: M009_V1_SPACE_CONTEXT_TRANSFER_VERSION, up: M009_V1_SPACE_CONTEXT_TRANSFER },
  { version: M010_V1_SPACE_SHARING_ACCESS_VERSION, up: M010_V1_SPACE_SHARING_ACCESS },
  { version: M011_V1_SYNC_RUNTIME_VERSION, up: M011_V1_SYNC_RUNTIME },
  { version: M012_V1_DEVICE_IDENTITIES_VERSION, up: M012_V1_DEVICE_IDENTITIES },
  { version: M013_V1_SPACE_PRESET_APPLICATIONS_VERSION, up: M013_V1_SPACE_PRESET_APPLICATIONS },
  { version: M014_V1_SPACE_TEMPLATE_OWNERS_VERSION, up: M014_V1_SPACE_TEMPLATE_OWNERS },
  { version: M015_V1_GATEWAY_CAPABILITY_GRANTS_VERSION, up: M015_V1_GATEWAY_CAPABILITY_GRANTS },
  { version: M016_V1_VOICE_USAGE_EVENTS_VERSION, up: M016_V1_VOICE_USAGE_EVENTS },
  { version: M017_V1_CONNECTOR_ARCHITECTURE_VERSION, up: M017_V1_CONNECTOR_ARCHITECTURE },
  { version: M018_V1_PROVIDER_SECRET_REFS_VERSION, up: M018_V1_PROVIDER_SECRET_REFS },
  { version: M019_V1_SPACE_MCP_ENDPOINTS_VERSION, up: M019_V1_SPACE_MCP_ENDPOINTS },
  { version: M020_V1_SPACE_EXTERNAL_AGENT_BINDINGS_VERSION, up: M020_V1_SPACE_EXTERNAL_AGENT_BINDINGS },
  { version: M021_V1_KNOWLEDGE_BASE_ENTRIES_VERSION, up: M021_V1_KNOWLEDGE_BASE_ENTRIES },
  { version: M022_V2_GATEWAY_SKILL_CATALOG_VERSION, up: M022_V2_GATEWAY_SKILL_CATALOG },
  { version: M023_V2_AGENT_PRESETS_VERSION, up: M023_V2_AGENT_PRESETS },
  { version: M024_V2_ASSIGNMENT_PROMPT_CONTEXT_VERSION, up: M024_V2_ASSIGNMENT_PROMPT_CONTEXT },
  { version: M025_V2_SCHEDULER_JOBS_VERSION, up: M025_V2_SCHEDULER_JOBS },
  { version: M026_V2_SHARE_RELAY_METADATA_VERSION, up: M026_V2_SHARE_RELAY_METADATA },
  { version: M027_V2_SPACE_WORKSPACE_PROJECT_META_VERSION, up: M027_V2_SPACE_WORKSPACE_PROJECT_META },
  { version: M028_V3_SPACE_WORKSPACE_METADATA_COLUMNS_VERSION, up: M028_V3_SPACE_WORKSPACE_METADATA_COLUMNS },
  { version: M029_V2_COLLABORATION_CHANGESETS_VERSION, up: M029_V2_COLLABORATION_CHANGESETS },
  { version: M030_V1_PROVIDER_CONFIGS_VERSION, up: M030_V1_PROVIDER_CONFIGS },
  { version: M031_V2_CHAT_SURFACE_V2_VERSION, up: M031_V2_CHAT_SURFACE_V2 },
  { version: M032_V2_TURNS_REPLY_TO_TURN_ID_VERSION, up: M032_V2_TURNS_REPLY_TO_TURN_ID },
  { version: M033_V2_PROVIDER_CONNECTION_STATES_NAMESPACE_VERSION, up: M033_V2_PROVIDER_CONNECTION_STATES_NAMESPACE },
  { version: M034_V2_TURNS_SPACE_ACTOR_INDEX_VERSION, up: M034_V2_TURNS_SPACE_ACTOR_INDEX },
  { version: M035_V2_RUNTIME_RESET_LEDGER_VERSION, up: M035_V2_RUNTIME_RESET_LEDGER },
  { version: M036_V2_PROVIDER_CONFIG_NATIVE_CLI_TOOLS_VERSION, up: M036_V2_PROVIDER_CONFIG_NATIVE_CLI_TOOLS },
  { version: M037_V2_PROVIDER_CONFIG_AUTH_MODE_VERSION, up: M037_V2_PROVIDER_CONFIG_AUTH_MODE },
  { version: M038_V2_USAGE_RECORD_TOKEN_ACCURACY_VERSION, up: M038_V2_USAGE_RECORD_TOKEN_ACCURACY },
  { version: M039_V2_SPACE_LIFECYCLE_TIMESTAMPS_VERSION, up: M039_V2_SPACE_LIFECYCLE_TIMESTAMPS },
  { version: M040_V2_GATEWAY_WORKSPACE_DEFAULTS_VERSION, up: M040_V2_GATEWAY_WORKSPACE_DEFAULTS },
  { version: M041_V2_GATEWAY_RUNTIME_DEFAULTS_VERSION, up: M041_V2_GATEWAY_RUNTIME_DEFAULTS },
  { version: M042_V2_GATEWAY_EXTERNAL_CONNECTIVITY_VERSION, up: M042_V2_GATEWAY_EXTERNAL_CONNECTIVITY },
  { version: M043_V3_IDENTITY_PERSONAS_VERSION, up: M043_V3_IDENTITY_PERSONAS },
  { version: M044_V4_SPACE_WORKSPACE_MANAGED_FOLDER_NAME_VERSION, up: M044_V4_SPACE_WORKSPACE_MANAGED_FOLDER_NAME },
  { version: M045_V5_VOICE_USAGE_CHANNEL_AND_PROVIDER_REGISTRY_VERSION, up: M045_V5_VOICE_USAGE_CHANNEL_AND_PROVIDER_REGISTRY },
  { version: M046_V6_GATEWAY_LINKED_SKILL_INDEX_VERSION, up: M046_V6_GATEWAY_LINKED_SKILL_INDEX },
  { version: M047_V7_CONCIERGE_ESCALATION_REQUESTS_VERSION, up: M047_V7_CONCIERGE_ESCALATION_REQUESTS },
  { version: M048_V8_WORKBENCH_VERSION, up: M048_V8_WORKBENCH },
  { version: M049_V9_AGENT_USAGE_SESSION_RUNTIME_METADATA_VERSION, up: M049_V9_AGENT_USAGE_SESSION_RUNTIME_METADATA },
  { version: M050_V10_WORKBENCH_EXECUTION_CONTEXT_VERSION, up: M050_V10_WORKBENCH_EXECUTION_CONTEXT },
  { version: M051_V11_GATEWAY_EXTERNAL_CONNECTIVITY_FUNNEL_VERSION, up: M051_V11_GATEWAY_EXTERNAL_CONNECTIVITY_FUNNEL },
  { version: M052_V12_INVITE_TOKENS_VERSION, up: M052_V12_INVITE_TOKENS },
  { version: M053_V13_APPLE_NOTIFICATIONS_VERSION, up: M053_V13_APPLE_NOTIFICATIONS },
  { version: M054_V14_RUNTIME_LEDGER_TURN_ID_VERSION, up: M054_V14_RUNTIME_LEDGER_TURN_ID },
];

export { SEED_STATEMENTS };
