apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: spaceskit-gateway-pdb
  labels:
    app: spaceskit-gateway
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: spaceskit-gateway
