/**
 * ExperienceRepository — CRUD for the `experiences` table.
 *
 * Stores space-level experience records generated by the ExperienceGenerator
 * after a space completes execution.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ExperienceRow {
  experience_id: string;
  space_id: string;
  summary: string;
  tags_json: string;
  lessons_json: string;
  status: string;
  created_at: string;
  updated_at: string;
}

export interface CreateExperienceInput {
  experienceId: string;
  spaceId: string;
  summary: string;
  tags?: string[];
  lessons?: string[];
}

export interface AgentObservationRow {
  observation_id: string;
  experience_id: string;
  agent_id: string;
  observation: string;
  strengths_json: string;
  weaknesses_json: string;
  created_at: string;
}

export interface CreateObservationInput {
  observationId: string;
  experienceId: string;
  agentId: string;
  observation: string;
  strengths?: string[];
  weaknesses?: string[];
}

// ---------------------------------------------------------------------------
// Repository
// ---------------------------------------------------------------------------

import type { Database } from "bun:sqlite";

export class ExperienceRepository {
  private db: Database;

  constructor(db: Database) {
    this.db = db;
    this.initSchema();
  }

  private initSchema(): void {
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS experiences (
        experience_id TEXT PRIMARY KEY,
        space_id TEXT NOT NULL,
        summary TEXT NOT NULL DEFAULT '',
        tags_json TEXT DEFAULT '[]',
        lessons_json TEXT DEFAULT '[]',
        status TEXT NOT NULL DEFAULT 'draft',
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      );
      CREATE INDEX IF NOT EXISTS idx_experiences_space ON experiences(space_id);
      CREATE INDEX IF NOT EXISTS idx_experiences_status ON experiences(status);

      CREATE TABLE IF NOT EXISTS agent_observations (
        observation_id TEXT PRIMARY KEY,
        experience_id TEXT NOT NULL REFERENCES experiences(experience_id) ON DELETE CASCADE,
        agent_id TEXT NOT NULL,
        observation TEXT NOT NULL DEFAULT '',
        strengths_json TEXT DEFAULT '[]',
        weaknesses_json TEXT DEFAULT '[]',
        created_at TEXT NOT NULL
      );
      CREATE INDEX IF NOT EXISTS idx_observations_experience ON agent_observations(experience_id);
      CREATE INDEX IF NOT EXISTS idx_observations_agent ON agent_observations(agent_id);
    `);
  }

  // ---- Experiences ----

  create(input: CreateExperienceInput): ExperienceRow {
    const now = new Date().toISOString();
    this.db.prepare(`
      INSERT INTO experiences (experience_id, space_id, summary, tags_json, lessons_json, status, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, 'draft', ?, ?)
    `).run(
      input.experienceId,
      input.spaceId,
      input.summary,
      JSON.stringify(input.tags ?? []),
      JSON.stringify(input.lessons ?? []),
      now,
      now,
    );

    return this.getById(input.experienceId)!;
  }

  getById(experienceId: string): ExperienceRow | null {
    return this.db.prepare(
      "SELECT * FROM experiences WHERE experience_id = ?",
    ).get(experienceId) as ExperienceRow | null;
  }

  listBySpace(spaceId: string, limit = 50): ExperienceRow[] {
    return this.db.prepare(
      "SELECT * FROM experiences WHERE space_id = ? ORDER BY created_at DESC LIMIT ?",
    ).all(spaceId, limit) as ExperienceRow[];
  }

  listByAgent(agentId: string, limit = 50): ExperienceRow[] {
    return this.db.prepare(`
      SELECT DISTINCT e.* FROM experiences e
      JOIN agent_observations o ON e.experience_id = o.experience_id
      WHERE o.agent_id = ?
      ORDER BY e.created_at DESC LIMIT ?
    `).all(agentId, limit) as ExperienceRow[];
  }

  updateStatus(experienceId: string, status: string): void {
    this.db.prepare(
      "UPDATE experiences SET status = ?, updated_at = ? WHERE experience_id = ?",
    ).run(status, new Date().toISOString(), experienceId);
  }

  updateSummary(experienceId: string, summary: string): void {
    this.db.prepare(
      "UPDATE experiences SET summary = ?, updated_at = ? WHERE experience_id = ?",
    ).run(summary, new Date().toISOString(), experienceId);
  }

  // ---- Agent Observations ----

  createObservation(input: CreateObservationInput): AgentObservationRow {
    const now = new Date().toISOString();
    this.db.prepare(`
      INSERT INTO agent_observations (observation_id, experience_id, agent_id, observation, strengths_json, weaknesses_json, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?)
    `).run(
      input.observationId,
      input.experienceId,
      input.agentId,
      input.observation,
      JSON.stringify(input.strengths ?? []),
      JSON.stringify(input.weaknesses ?? []),
      now,
    );

    return this.getObservationById(input.observationId)!;
  }

  getObservationById(observationId: string): AgentObservationRow | null {
    return this.db.prepare(
      "SELECT * FROM agent_observations WHERE observation_id = ?",
    ).get(observationId) as AgentObservationRow | null;
  }

  listObservationsByExperience(experienceId: string): AgentObservationRow[] {
    return this.db.prepare(
      "SELECT * FROM agent_observations WHERE experience_id = ? ORDER BY created_at",
    ).all(experienceId) as AgentObservationRow[];
  }

  listObservationsByAgent(agentId: string, limit = 50): AgentObservationRow[] {
    return this.db.prepare(
      "SELECT * FROM agent_observations WHERE agent_id = ? ORDER BY created_at DESC LIMIT ?",
    ).all(agentId, limit) as AgentObservationRow[];
  }
}
