import { describe, expect, test } from "bun:test";
import {
  mapInfraPulseAgentRow,
  mapInfraPulseSnapshot,
} from "../src/services/agent-presence-normalizers.js";

/**
 * A representative `/api/agent-presence` row as infra-pulse's detector emits it:
 * string `provider`/`status`, kebab-case statuses, fractional epoch-ms `at`.
 */
function rawRow(overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    key: "claude:sess-1",
    provider: "claude",
    sessionId: "sess-1",
    cwd: "/Users/caruso/code/spaces",
    status: "question",
    summary: "Which migration strategy?",
    options: [
      { label: "Option A", description: "fork-resume" },
      { label: "Option B" },
    ],
    hash: "abc123",
    at: 1_700_000_000_123.5,
    live: true,
    ...overrides,
  };
}

describe("mapInfraPulseAgentRow", () => {
  test("maps every field onto the JSON payload shape, string enums included", () => {
    const row = mapInfraPulseAgentRow(rawRow());
    expect(row).not.toBeNull();
    expect(row!.key).toBe("claude:sess-1");
    expect(row!.provider).toBe("claude");
    expect(row!.sessionId).toBe("sess-1");
    expect(row!.cwd).toBe("/Users/caruso/code/spaces");
    expect(row!.status).toBe("question");
    expect(row!.summary).toBe("Which migration strategy?");
    expect(row!.hash).toBe("abc123");
    // `at` is a fractional epoch-ms double — the fraction must survive.
    expect(row!.at).toBe(1_700_000_000_123.5);
    expect(row!.live).toBe(true);
    expect(row!.options).toEqual([
      { label: "Option A", description: "fork-resume" },
      { label: "Option B", description: "" },
    ]);
  });

  test("maps each provider and normalizes kebab-case statuses to snake_case unions", () => {
    expect(mapInfraPulseAgentRow(rawRow({ provider: "codex" }))!.provider).toBe("codex");
    expect(mapInfraPulseAgentRow(rawRow({ provider: "opencode" }))!.provider).toBe("opencode");
    expect(mapInfraPulseAgentRow(rawRow({ status: "turn-end" }))!.status).toBe("turn_end");
    expect(mapInfraPulseAgentRow(rawRow({ status: "idle-dead" }))!.status).toBe("idle_dead");
    expect(mapInfraPulseAgentRow(rawRow({ status: "permission" }))!.status).toBe("permission");
  });

  test("unknown provider / status degrade to 'unspecified' rather than throwing", () => {
    const row = mapInfraPulseAgentRow(rawRow({ provider: "gemini", status: "thinking" }));
    expect(row!.provider).toBe("unspecified");
    expect(row!.status).toBe("unspecified");
  });

  test("synthesizes a key from provider+sessionId when key is missing", () => {
    const row = mapInfraPulseAgentRow(rawRow({ key: undefined, provider: "codex", sessionId: "xyz" }));
    expect(row!.key).toBe("codex:xyz");
  });

  test("drops a row with no key and no sessionId", () => {
    expect(mapInfraPulseAgentRow(rawRow({ key: undefined, sessionId: undefined }))).toBeNull();
  });

  test("tolerates non-object / partial rows", () => {
    expect(mapInfraPulseAgentRow(null)).toBeNull();
    expect(mapInfraPulseAgentRow("nope")).toBeNull();
    const partial = mapInfraPulseAgentRow({ key: "claude:p", at: "not-a-number", options: "nope" });
    expect(partial!.cwd).toBe("");
    expect(partial!.at).toBe(0);
    expect(partial!.options).toEqual([]);
    expect(partial!.live).toBe(false);
  });
});

describe("mapInfraPulseSnapshot", () => {
  test("maps the full body and parses the ISO generatedAt to epoch-ms", () => {
    const snapshot = mapInfraPulseSnapshot({
      generatedAt: "2026-06-29T12:00:00.000Z",
      total: 1,
      agents: [rawRow()],
    });
    expect(snapshot.agents).toHaveLength(1);
    expect(snapshot.generatedAt).toBe(Date.parse("2026-06-29T12:00:00.000Z"));
  });

  test("skips malformed rows without dropping the good ones", () => {
    const snapshot = mapInfraPulseSnapshot({
      generatedAt: "2026-06-29T12:00:00.000Z",
      agents: [rawRow(), null, { provider: "claude" }, rawRow({ key: "codex:2", provider: "codex" })],
    });
    expect(snapshot.agents.map((a) => a.key)).toEqual(["claude:sess-1", "codex:2"]);
  });

  test("empty / missing agents array yields an empty snapshot", () => {
    expect(mapInfraPulseSnapshot({}).agents).toEqual([]);
    expect(mapInfraPulseSnapshot({ agents: "nope" as unknown }).agents).toEqual([]);
  });
});

describe("contract fixtures (drift check against @agent-presence/contracts)", () => {
  // Committed fixtures generated by the infra-pulse-side contracts package
  // (`bun run gen-fixtures -- --out test/fixtures/agent-presence`). If the
  // producer's wire format changes, these tests fail here instead of the
  // board silently rendering "unspecified" rows at runtime.
  const fixturesDir = new URL("./fixtures/agent-presence/", import.meta.url);

  test("every session-row fixture normalizes without degrading to unspecified", async () => {
    const rows = (await Bun.file(new URL("session-rows.json", fixturesDir).pathname).json()) as Record<
      string,
      Record<string, unknown>
    >;
    for (const [status, raw] of Object.entries(rows)) {
      const mapped = mapInfraPulseAgentRow(raw);
      expect(mapped).not.toBeNull();
      expect(mapped!.provider).not.toBe("unspecified");
      expect(mapped!.status).not.toBe("unspecified");
      expect(mapped!.status).toBe(status.replace("-", "_"));
      expect(mapped!.key).toBe(String(raw.key));
      expect(mapped!.hash).toBe(String(raw.hash));
    }
  });

  test("the presence-response envelope maps losslessly", async () => {
    const body = (await Bun.file(new URL("presence-response.json", fixturesDir).pathname).json()) as Record<
      string,
      unknown
    >;
    const snapshot = mapInfraPulseSnapshot(body);
    expect(snapshot.agents).toHaveLength((body.agents as unknown[]).length);
    expect(snapshot.generatedAt).toBe(Date.parse(String(body.generatedAt)));
  });
});
