export const JIRA_CLI_SKILL_ENTRY_ID = "connector/jira-cli";

export const JIRA_CLI_SKILL_SEED = {
  skillId: JIRA_CLI_SKILL_ENTRY_ID,
  name: "Jira CLI Connector",
  description: "Thin guidance for using the managed Jira CLI tools safely and efficiently.",
  sourceRef: "spaceskit:connector/jira-cli/skill/v2",
  tags: ["connector", "jira", "cli", "external-gateway", "tools"],
  contentMarkdown: [
    "# Jira CLI Connector",
    "",
    "Use this when the external gateway exposes the managed `jira.*` CLI tools.",
    "",
    "## Responsibilities",
    "- Prefer targeted Jira reads before mutations.",
    "- Keep searches narrow with project, assignee, status, limit, or targeted JQL filters.",
    "- Use the task-shaped `jira.*` tools instead of inventing raw shell commands.",
    "- Treat mutations as operator-visible actions that usually require approval.",
    "",
    "## Read-First Guidance",
    "- Start with `jira.me` or `jira.serverinfo` when host Jira context is uncertain.",
    "- For discovery, start with a narrow `jira.issue.list`, `jira.epic.list`, or `jira.sprint.list` using `detail: \"compact\"` (the default) and an explicit `limit`.",
    "- Use `jira.issue.view` once you have specific issue keys and need full Jira fields or comments.",
    "- Keep outputs small; prefer exact issue keys, precise filters, and a bounded `limit` over broad scans.",
    "- Do not page-scan Jira with offset pagination. The wrapper rejects non-zero offsets because `jira-cli` 1.7.x can return duplicate pages.",
    "- Do not put `ORDER BY` inside `jql`; pass `orderBy` and `reverse` separately.",
    "",
    "## Mutation Guidance",
    "- Read the latest issue before `jira.issue.edit`, `jira.issue.move`, `jira.issue.assign`, or comment/worklog changes.",
    "- Use `jira.issue.comment.add` for concise operator-readable updates.",
    "- Treat `jira.sprint.close` as destructive and require a clear user intent before invoking it.",
    "",
    "## Output Expectations",
    "- Jira tools return JSON envelopes with `ok`, `operation`, `summary`, and optional `data`/`refs`.",
    "- `jira.issue.list`, `jira.epic.list`, and `jira.sprint.list` return compact summary rows by default; switch to `detail: \"raw\"` only for narrow reads.",
    "- Some list operations normalize text into JSON when `jira-cli` does not provide raw JSON output.",
    "",
    "## Failure Handling",
    "- If Jira auth is degraded, explain the host-level Jira configuration problem instead of retrying blindly.",
    "- Do not suggest storing Jira secrets inside Spaces for this connector; it reuses host Jira config.",
  ].join("\n"),
} as const;
