import { USER_ESCALATION_SKILL_ID } from "@spaceskit/core";

export interface MainSpaceSystemSkillSeed {
  skillId: string;
  name: string;
  description: string;
  contentMarkdown: string;
  sourceRef: string;
  tags: string[];
  status: "active";
}

const COMMAND_REGISTRY_V1 = [
  "list_spaces",
  "create_space",
  "list_skills",
  "create_skill",
  "handoff_space",
] as const;

const SHARED_SUFFIX = [
  "## Command Registry v1",
  "These are the currently supported control-plane commands:",
  ...COMMAND_REGISTRY_V1.map((command) => `- \`${command}\``),
  "",
  "This list is intentionally versioned and expandable.",
  "When a permanent command registry is provided, update this section in place.",
].join("\n");

export const MAIN_SPACE_SYSTEM_SKILLS: readonly MainSpaceSystemSkillSeed[] = [
  {
    skillId: "system/spaces-skill",
    name: "Spaces Skill",
    description: "Core Spaces app behavior, capabilities, constraints, and space operations guidance.",
    contentMarkdown: [
      "# Spaces Skill",
      "Use this as the canonical context for how Spaces works today.",
      "",
      "## Responsibilities",
      "- Describe current app capabilities and known limitations without guessing.",
      "- Explain space lifecycle behavior with clear operational steps.",
      "- Route control-surface actions through gateway orchestration contracts.",
      "",
      "## Current Capability Scope",
      "- Main chat shell with gateway-backed spaces.",
      "- Space creation, agent assignment, skill assignment, and workspace operations.",
      "- Scheduler, orchestration journal, and gateway admin surfaces.",
      "",
      "## Current Limitation Notes",
      "- Space archive/delete transport APIs are not yet shipped.",
      "- Main-space permanence is enforced by startup defaults and app-local guardrails.",
      "",
      SHARED_SUFFIX,
    ].join("\n"),
    sourceRef: "spaceskit:system/main-space/spaces-skill/v1",
    tags: ["system", "spaces", "main-space", "operations"],
    status: "active",
  },
  {
    skillId: "system/moderator-skill",
    name: "Moderator Skill",
    description: "Multi-agent coordination policy, scope control, and escalation behavior.",
    contentMarkdown: [
      "# Moderator Skill",
      "Use this to coordinate multiple agents with predictable execution discipline.",
      "",
      "## Responsibilities",
      "- Decide whether a request is simple or multi-agent worthy.",
      "- Keep tasks scoped; avoid unnecessary delegation.",
      "- Assign agents explicitly and maintain role clarity.",
      "- Escalate when blockers or policy constraints prevent safe execution.",
      "",
      "## Decision Rules",
      "- Prefer single-agent execution for focused tasks.",
      "- Use multi-agent only when work clearly benefits from decomposition.",
      "- Track handoff boundaries and ensure one final synthesized answer.",
      "",
      "## Handoff Guidance",
      "- Choose target space and agent intentionally.",
      "- Provide concise task framing, constraints, and expected output.",
      "",
      SHARED_SUFFIX,
    ].join("\n"),
    sourceRef: "spaceskit:system/main-space/moderator-skill/v1",
    tags: ["system", "moderation", "coordination", "main-space"],
    status: "active",
  },
  {
    skillId: "system/master-skill",
    name: "Master Skill",
    description: "Primary operational reference for architecture, docs locations, defaults, and management flows.",
    contentMarkdown: [
      "# Master Skill",
      "Use this as the top-level guide for how the app and gateway operate.",
      "",
      "## Responsibilities",
      "- Explain system architecture and runtime profile behavior.",
      "- Point to documentation and canonical planning sources.",
      "- Describe default commands/capabilities exposed by the current control plane.",
      "- Explain how to create/manage spaces, templates, agents, and experiences.",
      "",
      "## Documentation Map",
      "- Repository root: `README.md`",
      "- Gateway docs: `gateway/README.md` and `gateway/docs/`",
      "- Planning canon: `_planning/WORKFLOW-INSTRUCTION.md`, `_planning/WHAT-TO-DO-NEXT.md`",
      "",
      "## Operational Defaults",
      "- Main-space bootstrap is profile-aware (`embedded` and `external`).",
      "- Main-space coordination is expected to run through control-plane orchestration commands.",
      "",
      SHARED_SUFFIX,
    ].join("\n"),
    sourceRef: "spaceskit:system/main-space/master-skill/v1",
    tags: ["system", "master", "docs", "orchestration", "main-space"],
    status: "active",
  },
];

export const CONCIERGE_SKILLS: readonly MainSpaceSystemSkillSeed[] = [
  {
    skillId: USER_ESCALATION_SKILL_ID,
    name: "User Escalation",
    description: "Trusted-agent policy for requesting user input, sending structured notifications, and escalating urgent requests to concierge calls.",
    contentMarkdown: [
      "# User Escalation",
      "",
      "## Responsibilities",
      "- Use concierge escalation only when a human decision is required to continue safely.",
      "- Rewrite agent needs into concise user-facing copy before delivery.",
      "- Prefer structured notification requests and waiting over immediate interruption.",
      "",
      "## Decision Rules",
      "- Use `concierge.request_user_input` for blocked decisions, approvals, and revisions.",
      "- Keep `responseMode` set to `structured` and limit `allowedResponses` to the smallest useful set.",
      "- Use `fallbackPolicy=urgent_call_after_timeout` only when the request is urgent and waiting would risk the task or user experience.",
      "- Never assume an urgent concierge call is allowed unless the request explicitly opts into it.",
      "",
      "## Constraints",
      "- Default path: notification plus app deep-link.",
      "- Do not ask for arbitrary free-form text through the tool in v1.",
      "- If the local Apple concierge lane needs escalation, hand off to the gateway-backed concierge path first.",
      "",
      SHARED_SUFFIX,
    ].join("\n"),
    sourceRef: "spaceskit:system/user-escalation/v1",
    tags: ["system", "concierge", "escalation", "trusted-agent"],
    status: "active",
  },
  {
    skillId: "role/concierge-operations",
    name: "Concierge Operations",
    description: "Operational procedures for the concierge agent: space navigation, management, cross-space awareness, and escalation.",
    contentMarkdown: [
      "# Concierge Operations",
      "",
      "## Space Navigation",
      "- List all active spaces with last-activity timestamps.",
      "- Switch the user's view to a named space.",
      "- Summarize recent activity in a space (last N turns, pending feedback, stale agents).",
      "",
      "## Space Management",
      "- Create spaces from templates — ask which template if ambiguous.",
      "- Archive inactive spaces after confirming with the user.",
      "- Assign or reassign agents to spaces.",
      "- Update space goals and agent spawn context.",
      "",
      "## Cross-Space Awareness",
      "- Report pending feedback requests across all spaces.",
      "- Identify stale spaces (no activity in 24+ hours).",
      "- Surface spaces with failed or errored turns.",
      "",
      "## Escalation Paths",
      "- Route complex analytical or creative tasks to the main agent or a team space.",
      "- When user input is required, prefer `concierge.request_user_input` with a short structured question.",
      "- Only opt into automatic concierge calls for urgent requests with explicit fallback permission.",
      "- Suggest creating a team space when a task clearly benefits from multi-agent decomposition.",
      "- Never attempt multi-step tool chains — hand off to the appropriate specialist.",
      "",
      "## Behavioral Constraints",
      "- Keep responses under 3 sentences for operational actions.",
      "- After completing an action, suggest the next logical step.",
      "- Ask ONE clarifying question when uncertain — never present a list of options.",
      "- Keep escalation copy short, operational, and easy to answer from a notification.",
    ].join("\n"),
    sourceRef: "spaceskit:role/concierge-operations/v1",
    tags: ["role", "concierge", "operations", "navigation"],
    status: "active",
  },
];

export const MAIN_SPACE_SYSTEM_SKILL_IDS = MAIN_SPACE_SYSTEM_SKILLS.map((skill) => skill.skillId);
export const TRUSTED_AGENT_SYSTEM_SKILL_IDS = [USER_ESCALATION_SKILL_ID] as const;
