import type { ConnectorFamilyRecord } from "./connector-admin-service-types.js";

export const DEFAULT_CONNECTOR_FAMILIES: Array<Omit<ConnectorFamilyRecord, "createdAt" | "updatedAt">> = [
  {
    familyId: "apple-calendar-eventkit",
    displayName: "Apple Calendar (EventKit)",
    kind: "capability",
    runtime: "adapter",
    trustClass: "embedded_safe",
    embeddedEnabled: true,
    capabilityTypes: ["calendar"],
    features: { platform: "apple", native: true },
  },
  {
    familyId: "apple-reminders-eventkit",
    displayName: "Apple Reminders (EventKit)",
    kind: "capability",
    runtime: "adapter",
    trustClass: "embedded_safe",
    embeddedEnabled: true,
    capabilityTypes: ["lists"],
    features: { platform: "apple", native: true },
  },
  {
    familyId: "apple-mail-mailkit",
    displayName: "Apple Mail (MailKit)",
    kind: "hybrid",
    runtime: "adapter",
    trustClass: "embedded_safe",
    embeddedEnabled: true,
    capabilityTypes: ["email"],
    features: { platform: "apple", native: true },
  },
  {
    familyId: "apple-contacts-contactsframework",
    displayName: "Apple Contacts (Contacts.framework)",
    kind: "capability",
    runtime: "adapter",
    trustClass: "embedded_safe",
    embeddedEnabled: true,
    capabilityTypes: ["contacts"],
    features: { platform: "apple", native: true },
  },
  {
    familyId: "apple-notifications-usernotifications",
    displayName: "Apple Notifications (UserNotifications)",
    kind: "hybrid",
    runtime: "adapter",
    trustClass: "embedded_safe",
    embeddedEnabled: true,
    capabilityTypes: ["notifications"],
    features: { platform: "apple", native: true },
  },
  {
    familyId: "whatsapp-cloud",
    displayName: "WhatsApp Cloud API",
    kind: "channel",
    runtime: "connector",
    trustClass: "external_only",
    embeddedEnabled: false,
    capabilityTypes: ["messaging", "notifications"],
    features: { channel: "whatsapp", provider: "meta" },
  },
  {
    familyId: "discord-bot",
    displayName: "Discord Bot API",
    kind: "channel",
    runtime: "connector",
    trustClass: "external_only",
    embeddedEnabled: false,
    capabilityTypes: ["messaging", "notifications"],
    features: { channel: "discord" },
  },
];

